name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # assuming you're using the 'main' branch. Change to 'master' if you're using the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Jekyll site
      run: |
        docker run \
          -v $PWD/truck-roll-calculator:/srv/jekyll \
          -v $PWD/truck-roll-calculator/_site:/srv/jekyll/_site \
          jekyll/jekyll:latest \
          jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./truck-roll-calculator/_site
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy to GitHub Pages'
