name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          cd truck-roll-calculator
          gem install bundler
          bundle install

      - name: Build and deploy
        run: |
          cd truck-roll-calculator
          bundle exec jekyll build
          ls _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: truck-roll-calculator/_site
